### PR TITLE
Use spaces instead of tabs

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by michaelsproul** [comment]
Haha, I thought I might get in trouble for this.

Apart from the tabs, my code exhibits perfectly fine PEP8 style, and I'm inclined to keep the tabs...

**Comment by prologic** [comment]
Haha trouble with tabs is that you run into inconsistency problems rather easily unless you ensure all developers have sensible editor settings which you can't guarantee :) (_I use vim!_) -- That being said though, there were some PEP8 compliance issues that causes flake8 which I use from syntastic (_a vim plugin_) that made my editor go all **red** :/

I hope we don't get into contention over this :)

**Comment by denbeigh2000** [comment]
I would strongly suggest that you merge @therealprologic's changes, it is important to adhere to the style convention. I have many-a-time tried to modify and run others' code on my environment, only to need to resolve mixed whitespace issues (esp with python3, which doesn't allow for mixed tab/space indentation).

Remember, the more consistency you can achieve, the less that can go wrong. It's part of the style guide for a reason :)
http://legacy.python.org/dev/peps/pep-0008/#tabs-or-spaces

**Comment by prologic** [comment]
Even Python 2 does not permit mixing of white space characters :)

I agree, but my opinion had already been made by this PR :)

**Comment by michaelsproul** [comment]
All fixed ;)

75767718b5eb1158b3c13c96b559ae760b487c3c

**Comment by prologic** [comment]
@gnusouth Look I'm going to be blunt here. So apologies in advance.

a) You rejected my PR and changesets which now make it hard for me to contribute. If you're not happy with suggested changes, say so! I now have to strip two chagnesets off my branch and force push. This is more work for me than it's worth.

b) This changeset of yours is not "good enough". It is still not PEP8 compliant and whilst editor settings in modules are great -- You would have to litter those across all your modules. It is far better to stick to a set of coding styles/guidelines that almost everyone agrees with. PEP8.

c) `xuino.py` still uses tabs. See: `W191    indentation contains tabs` from http://pep8.readthedocs.org/en/1.4.6/intro.html#error-codes

I would like to both use xuino and contribute to it; but right now you are making this quite difficulty. Sorry :/

**Comment by michaelsproul** [comment]
It really isn't that big a deal. This is my project, and I like tabs, so we'll use tabs.

Any linter that fires warnings as soon as it sees tabs is not worth using in my opinion. I'd be disabling that warning universally, to avoid future conflicts of this kind. You've still got `E101:     indentation contains mixed spaces and tabs`.

Resetting your tree and forcing a push isn't that hard, particularly as you haven't made any real changes!

I suggest you dive in and try the code, instead of worrying about packaging and code style.

**Comment by denbeigh2000** [comment]
A disappointing resolution.

**Comment by michaelsproul** [comment]
I'm not alone in preferring tabs for Python:

https://stackoverflow.com/questions/119562/tabs-versus-spaces-in-python-programming

http://forums.xkcd.com/viewtopic.php?f=40&t=58867

**Comment by prologic** [comment]
Disappointing for me too.

I'm sorry Michael, but I believe I will find another way to do Arduino
based development.
(_Something that uses more best practices, standards and more commonly
accepted coding styles_).

I'm not really interested in working with a project
that defies all kinds of standards (I'm talking Python here).

Thanks all the same though. Yes you're right
it may not seem like a "big deal" to you, but
I have a family, other proejcts and work commitments
so I can't really afford to change my workflows
and standards just to suit you (**nor can you it seems**).

The fact of the matter is (_despite how you or others feel_)
The use of spaces is more widely accepted as the optimal solution
for indention in almost any language. The fact that you choose to use
8 spaces to "display" your tabs (_from your recent vim/emacs commit_)
is astounding to me because you unnecessarily widen the display of the
source to a point where even 160 character wide terminals will not be
enough!

cheers
James

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Pull request closed without merging**
